### ISSUE TITLE
Implement Tab-Based Block Delimitation for Code Parsing

### ISSUE THREAD

**Issue by MRoiban** [MRoiban/pmx11#6]
## Description:
The objective is to implement a tab-based block delimitation system for code parsing. The provided Python snippet handles indentation to identify code blocks and translates conditional statements into assembly-like instructions. The code parses each line, determines the indentation, and outputs conditional jumps for `IF` statements.

## Code Snippet:
```python
current_indent = 0
for line in code:
    indent = count_leading_whitespace(line)
    
    if "IF" in line and ":" in line:
        condition = extract_condition(line)
        print(f"CMP {condition}, 0")
        print(f"JNE label_if_true_{label_counter}")
        print(f"JMP label_after_if_{label_counter}")
        current_indent += 1
    elif indent > current_indent:
        # We're inside a block, output the instruction
        print(f"label_if_true_{label_counter}:")
        print(f"   {line.strip()}")
    elif indent < current_indent:
        # End of block
        current_indent -= 1
        print(f"label_after_if_{label_counter}:")
```

## Expected Behavior:
- Code blocks are delimited by indentation levels (tabs or spaces).
- Conditional statements (like `IF` conditions) are parsed and translated into assembly-style `CMP`, `JNE`, and `JMP` instructions.
- Labels are dynamically generated for entering and exiting conditional blocks.

## Tasks:
- [ ] Implement logic to handle different indentation levels (tabs/spaces).
- [ ] Ensure proper handling of conditional statements and their translations into jumps.
- [ ] Add support for nested blocks based on indentation.
